######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 12 10:15:45 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += app.h photonmap.h world.h
SOURCES += app.cpp photonmap.cpp world.cpp
